RSiteSearch("arithmetic mean")
RSiteSearch("{mean}")
install.packages("sos")
findFunction("{arithmetic mean}")
library(sos)
findFn("{arithmetic mean}")
findFn("{arithmetic mean}",maxPages = 3)
???"{arithmetic mean}"(2)
install.packages("twitteR", dependencies = TRUE)
library(twitteR)
vignette('twitteR',package='twitteR')
.libPaths()
